apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mypod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        command:
          - git
          - clone
          - https://github.com/swati-zampal/gitRepo.git
          - /data
        volumeMounts:
          - name: myvolume
            mountPath: /data
      containers:
      - image: nginx
        name: mycont1
        ports:
          - containerPort: 80
        volumeMounts:
          - name: myvolume
            mountPath: /usr/share/nginx/html/
      volumes:
        - name: myvolume
          emptyDir: {}
